<?php

declare(strict_types=1);

return [
    'Santiago',
    'Sebastián',
    'Matías',
    'Mateo',
    'Nicolás',
    'Alejandro',
    'Diego',
    'Samuel',
    'Benjamín',
    'Daniel',
    'Joaquín',
    'Lucas',
    'Tomas',
    'Gabriel',
    'Martín',
    'David',
    'Emiliano',
    'Jerónimo',
    'Emmanuel',
    'Agustín',
    'Juan Pablo',
    'Juan José',
    'Andrés',
    'Thiago',
    'Leonardo',
    'Felipe',
    'Ángel',
    'Maximiliano',
    'Christopher',
    'Juan Diego',
    'Adrián',
    'Pablo',
    'Miguel Ángel',
    'Rodrigo',
    'Alexander',
    'Ignacio',
    'Emilio',
    'Dylan',
    'Bruno',
    'Carlos',
    'Vicente',
    'Valentino',
    'Santino',
    'Julián',
    'Juan Sebastián',
    'Aarón',
    'Lautaro',
    'Axel',
    'Fernando',
    'Ian',
    'Christian',
    'Javier',
    'Manuel',
    'Luciano',
    'Francisco',
    'Juan David',
    'Iker',
    'Facundo',
    'Rafael',
    'Alex',
    'Franco',
    'Antonio',
    'Luis',
    'Isaac',
    'Máximo',
    'Pedro',
    'Ricardo',
    'Sergio',
    'Eduardo',
    'Bautista',
    'Miguel',
    'Cristóbal',
    'Kevin',
    'Jorge',
    'Alonso',
    'Anthony',
    'Simón',
    'Juan',
    'Joshua',
    'Diego Alejandro',
    'Juan Manuel',
    'Mario',
    'Alan',
    'Josué',
    'Gael',
    'Hugo',
    'Matthew',
    'Ivan',
    'Damián',
    'Lorenzo',
    'Juan Martín',
    'Esteban',
    'Álvaro',
    'Valentín',
    'Dante',
    'Jacobo',
    'Jesús',
    'Camilo',
    'Juan Esteban',
    'Elías',

    // 100 most popular hispanic names: https://www.babycenter.com/0_100-most-popular-hispanic-baby-names-of-2011_10363639.bc
];
