<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\FederationController
 */
class FederationControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $federation = factory(\App\Federation::class)->create();

        $response = $this->get(route('create_federation', ['locale' => $federation->locale]));

        $response->assertOk();
        $response->assertViewIs('federations.create');

        // TODO: perform additional assertions
    }

    // test cases...
}
