<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\LineupController
 */
class LineupControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $lineup = factory(\App\Lineup::class)->create();
        $club = factory(\App\Club::class)->create();
        $lineup = factory(\App\Lineup::class)->create();

        $response = $this->get(route('edit_lineup', ['locale' => $lineup->locale, $club, 'squad' => $lineup->squad]));

        $response->assertOk();
        $response->assertViewIs();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $lineup = factory(\App\Lineup::class)->create();
        $lineup = factory(\App\Lineup::class)->create();

        $response = $this->post(route('update_lineup', ['locale' => $lineup->locale, $lineup]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
