<?php

declare(strict_types=1);

namespace Tests\Feature\Http\Controllers;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ManagerContractController
 */
final class ManagerContractControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $club = factory(\App\Models\Club::class)->create();

        $response = $this->get(route('apply_for_job', ['locale' => 'en', $club]));
        $response->assertStatus(302);

        $user = factory(User::class)->create();

        $response = $this->actingAs($user)->get(route('apply_for_job', ['locale' => 'en', $club]));
        $response->assertOk();
    }

    /**
     * @test
     */
    public function quit_job_returns_an_ok_response()
    {
        // $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $club = factory(\App\Models\Club::class)->create();
        $user = factory(User::class)->create();
        $manager_contract = factory(\App\ManagerContract::class)->create([
            'club_id' => $club->id, 'user_id' => $user->id,
        ]);

        $response = $this->actingAs($user)->get(route('quit_job', ['locale' => 'en', $club]));

        $response->assertOk();
        $response->assertViewIs('manager-contracts.quit');
        $response->assertViewHas('club');
        $response->assertViewHas('boardMessage');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $club = factory(\App\Models\Club::class)->create();
        $manager = factory(User::class)->create();
        $unmanagedClub = factory(\App\Models\Club::class)->create();
        $unemployedManager = factory(User::class)->create();
        factory(\App\ManagerContract::class)->create([
            'user_id' => $manager->id, 'club_id' => $club->id,
        ]);

        $response = $this->post(route('send_job_application', ['locale' => 'en']), [
            'club_id' => $club->id,
        ]);
        $response->assertStatus(302);

        $loggedIn = $this->actingAs($manager)->post(route('send_job_application', ['locale' => 'en']), [
            'club_id' => $club->id,
        ]);
        $loggedIn->assertStatus(302);

        $unemployed = $this->actingAs($unemployedManager)->post(route('send_job_application', ['locale' => 'en']), [
            'club_id' => $unmanagedClub->id,
        ]);
    }
}
