<?php

return [
    'Berlin',
    'Hamburg',
    'München',
    'Köln',
    'Frankfurt am Main',
    'Essen',
    'Stuttgart',
    'Dortmund',
    'Düsseldorf',
    'Bremen',
    'Hannover',
    'Leipzig',
    'Duisburg',
    'Nürnberg',
    'Dresden',
    'Wandsbek',
    'Bochum',
    'Bochum-Hordel',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Mannheim',
    'Marienthal',
    'Karlsruhe',
    'Hamburg-Nord',
    'Wiesbaden',
    'Münster',
    'Gelsenkirchen',
    'Aachen',
    'Mönchengladbach',
    'Augsburg',
    'Eimsbüttel',
    'Altona',
    'Chemnitz',
    'Braunschweig',
    'Krefeld',
    'Halle (Saale)',
    'Hamburg-Mitte',
    'Kiel',
    'Magdeburg',
    'Neue Neustadt',
    'Oberhausen',
    'Freiburg',
    'Lübeck',
    'Erfurt',
    'Harburg',
    'Hagen',
    'Rostock',
    'Kassel',
    'Hamm',
    'Mainz',
    'Saarbrücken',
    'Herne',
    'Mülheim',
    'Neukölln',
    'Osnabrück',
    'Solingen',
    'Ludwigshafen am Rhein',
    'Leverkusen',
    'Oldenburg',
    'Neuss',
    'Prenzlauer Berg',
    'Kreuzberg',
    'Potsdam',
    'Heidelberg',
    'Paderborn',
    'Darmstadt',
    'Würzburg',
    'Regensburg',
    'Wolfsburg',
    'Recklinghausen',
    'Göttingen',
    'Heilbronn',
    'Ingolstadt',
    'Ulm',
    'Bottrop',
    'Charlottenburg',
    'Bergedorf',
    'Pforzheim',
    'Offenbach',
    'Friedrichshain',
    'Bremerhaven',
    'Remscheid',
    'Berlin Schöneberg',
    'Schöneberg',
    'Nippes',
    'Reutlingen',
    'Fürth',
    'Moers',
    'Koblenz',
    'Siegen',
    'Bergisch Gladbach',
    'Jena',
    'Gera',
    'Marzahn',
    'Hildesheim',
    'Erlangen',
    'Witten',
    'Salzgitter',
    'Trier',

    // 100 largest cities from Italy: https://population.mongabay.com/population/italy/
];
