<?php

return [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Zaragoza',
    'Málaga',
    'Murica',
    'Palma',
    'Las Palma de Gran Canaria',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
    'Eixample',
    'L\'Hospitalet de Llobregat',
    'Latina',
    'Carabanchel',
    'A Coruña',
    'Puente de Vallecas',
    'Sant Martí',
    'Gasteiz / Vitoria',
    'Granada',
    'Elche',
    'Ciudad Lineal',
    'Oviedo',
    'Santa Cruz de Tenerife',
    'Fuencarral-El Pardo',
    'Badalona',
    'Cartagena',
    'Terrassa',
    'Jerez de la Frontera',
    'Sabadell',
    'Móstoles',
    'Alcalá de Henares',
    'Pamplona',
    'Fuenlabrada',
    'Almería',
    'Leganés',
    'San Sebastián',
    'Sants-Montjuïc',
    'Santander',
    'Castelló de la Plana',
    'Burgos',
    'Albacete',
    'Horta-Guinardó',
    'Alcorcón',
    'Getafe',
    'Nou Barris',
    'Hortaleza',
    'San Blas-Canillejas',
    'Salamanca',
    'Tetuán de las Victorias',
    'Logroño',
    'La Laguna',
    'Madrid Centro',
    'Huelva',
    'Arganzuela',
    'Badajoz',
    'Sarrià-Sant Gervasi',
    'Sant Andreu',
    'Salamanca',
    'Chamberí',
    'Usera',
    'Tarragona',
    'Chamartín',
    'Lleida',
    'Marbella',
    'León',
    'Villaverde',
    'Cadiz',
    'Retiro',
    'Dos Hermanas',
    'Mataró',
    'Gràcia',
    'Santa Coloma de Gramenet',
    'Torrejón de Ardoz',
    'Jaén',
    'Moncloa-Aravaca',
    'Algeciras',
    'Parla',
    'Delicias',
    'Ourense',
    'Alcobendas',
    'Reus',
    'Moratalaz',
    'Ciutat Vella',
    'Torrevieja',
    'Telde',
    'Barakaldo',
    'Lugo',
    'San Fernando',
    'Girona',
    'Santiago de Compostela',
    'Cáceres',
    'Lorca',
    'Coslada',
    'Talavera de la Reina',
    'El Puerto de Santa María',
    'Cornellà de Llobregat',

    // 100 largest cities from Spain: https://population.mongabay.com/population/spain/
];