<?php

declare(strict_types=1);

return [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Le Havre',
    'Cergy-Pontoise',
    'Saint-Étienne',
    'Toulon',
    'Angers',
    'Grenoble',
    'Dijon',
    'Nîmes',
    'Aix-en-Provence',
    'Saint-Quentin-en-Yvelines',
    'Brest',
    'Le Mans',
    'Amiens',
    'Tours',
    'Limoges',
    'Clermont-Ferrand',
    'Villeurbanne',
    'Besançon',
    'Orléans',
    'Metz',
    'Rouen',
    'Mulhouse',
    'Perpignan',
    'Caen',
    'Boulogne-Billancourt',
    'Nancy',
    'Argenteuil',
    'Saint-Denis',
    'Roubaix',
    'Tourcoing',
    'Montreuil',
    'Avignon',
    'Marseille 13',
    'Asnières-sur-Seine',
    'Nanterre',
    'Poitiers',
    'Versailles',
    'Courbevoie',
    'Créteil',
    'Pau',
    'Colombes',
    'Vitry-sur-Seine',
    'Aulnay-sous-Bois',
    'Marseille 08',
    'Marseille 15',
    'Marseille 09',
    'La Rochelle',
    'Champigny-sur-Marne',
    'Rueil-Malmaison',
    'Antibes',
    'Saint-Maur-des-Fossés',
    'Calais',
    'Béziers',
    'Dunkerque',
    'Aubervilliers',
    'Cannes',
    'Mérignac',
    'Bourges',
    'Saint-Nazaire',
    'Colmar',
    'Valence',
    'Quimper',
    'Drancy',
    'Noisy-le-Grand',
    'Villeneuve-d\'Ascq',
    'La Seyne-sur-Mer',
    'Levallois-Perret',
    'Marseille 14',
    'Chambéry',
    'Issy-les-Moulineaux',
    'Neuilly-sur-Seine',
    'Troyes',
    'Antony',
    'La Roche-sur-Yon',
    'Marseille 12',
    'Lorient',
    'Sarcelles',
    'Pessac',
    'Ivry-sur-Seine',
    'Évreux',
    'Vénissieux',
    'Cergy',
    'Clichy',
    'Marseille 11',
    'Saint-Quentin',
    'Niort',
    'Belfort',
    'Ajaccio',

    // 100 largest cities from France: https://population.mongabay.com/population/france/
];
