<?php

return [
    'London',
    'Birmingham',
    'Liverpool',
    'Nottingham',
    'Sheffield',
    'Bristol',
    'Glasgow',
    'Leicester',
    'Edinburgh',
    'Leeds',
    'Cardiff',
    'Manchester',
    'Stoke-on-Trent',
    'Coventry',
    'Sunderland',
    'Birkenhead',
    'Islington',
    'Reading',
    'Kingston upon Hull',
    'Preston',
    'Newport',
    'Swansea',
    'Bradford',
    'Southend-on-Sea',
    'Belfast',
    'Derby',
    'Plymouth',
    'Luton',
    'Wolverhampton',
    'City of Westminster',
    'Southampton',
    'Blackpool',
    'Milton Keynes',
    'Bexley',
    'Northampton',
    'Archway',
    'Norwich',
    'Dudley',
    'Aberdeen',
    'Portsmouth',
    'Newcastle upon Tyne',
    'Sutton',
    'Swindon',
    'Crawley',
    'Ipswich',
    'Wigan',
    'Croydon',
    'Walsall',
    'Mansfield',
    'Oxford',
    'Warrington',
    'Slough',
    'Bournemouth',
    'Petersborough',
    'Cambridge',
    'Doncaster',
    'York',
    'Poole',
    'Gloucester',
    'Burnley',
    'Huddersfield',
    'Telford',
    'Dundee',
    'Blackburn',
    'Basildon',
    'Middlesbrough',
    'Bolton',
    'Stockport',
    'Brighton',
    'West Bromwich',
    'Grimsby',
    'Hastings',
    'High Wycombe',
    'Watford',
    'Saint Peters',
    'Burton upon Trent',
    'Colchester',
    'Eastbourne',
    'Exeter',
    'Rotherham',
    'Cheltenham',
    'Lincoln',
    'Chesterfield',
    'Chelmsford',
    'Mendip',
    'Dagenham',
    'Basingstoke',
    'Maidstone',
    'Sutton Coldfield',
    'Bedford',
    'Oldham',
    'Enfield Town',
    'Woking',
    'St Helens',
    'Worcester',
    'Gillingham',
    'Becontree',
    'Worthing',
    'Rochdale',
    'Solihull',
    'Royal Leamington Spa',
    'Romford',
    'Bath',
    'Harlow',
    'Nuneaton',
    'High Peak',
    'Darlington',
    'Southport',
    'Chester',
    'Stevenage',
    'Wembley',
    'Grays',
    'Harrogate',
    'Hartlepool',
    'Londonderry County Borough',
    'Cannock',
    'Hemel Hempstead',
    'St Albans',
    'Redditch',
    'South Shields',
    'Derry',
    'Weston-super-Mare',
    'Halifax',
    'Beckenham',
    'Tamworth',
    'Scunthorpe',
    'Stockton-on-Tees',
    'Wakefield',
    'Carlisle',
    'Gateshead',
    'Lisburn',
    'Fylde',
    'Paisley',
    'Bracknell',
    'Newcastle under Lyme',
    'Battersea',
    'Crewe',
    'Chatham',
    'Hove',
    'Aylesbury',
    'East Kilbride',
    'Canary Wharf',
    'Rugby',
    'Salford',
    'Purley',
    'Guildford',
    'Shrewsbury',
    'Peckham',
    'Barnsley',
    'Lowestoft',

    // Top 150 of cities from United Kingdom: https://population.mongabay.com/population/united-kingdom/
];
