<?php

return [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Catania',
    'Bari',
    'Messina',
    'Verona',
    'Padova',
    'Trieste',
    'Brescia',
    'Prato',
    'Taranto',
    'Reggio Calabria',
    'Modena',
    'Livorno',
    'Cagliari',
    'Mestre',
    'Parma',
    'Foggia',
    'Reggio nell\'Emilia',
    'Acilia-Castel Fusano-Ostia Antica',
    'Salerno',
    'Perugia',
    'Monza',
    'Rimini',
    'Pescara',
    'Bergamo',
    'Vicenza',
    'Bolzano',
    'Andria',
    'Udine',
    'Siracusa',
    'Terni',
    'Forlì',
    'Novara',
    'Barletta',
    'Piacenza',
    'Ferrara',
    'Sassari',
    'Ancona',
    'La Spezia',
    'Torre del Greco',
    'Como',
    'Lucca',
    'Ravenna',
    'Lecce',
    'Trento',
    'Giugliano in Campania',
    'Busto Arsizio',
    'Lido di Ostia',
    'Cesena',
    'Catanzaro',
    'Brindisi',
    'Marsala',
    'Treviso',
    'Pesaro',
    'Pisa',
    'Varese',
    'Sesto San Giovanni',
    'Arezzo',
    'Latina',
    'Gela',
    'Pistoia',
    'Caserta',
    'Cinisello Balsamo',
    'Lamezia Terme',
    'Altamura',
    'Guidonia Montecelio',
    'Quartu Sant\'Elena',
    'Pavia',
    'Castellammare di Stabia',
    'Massa',
    'Alessandria',
    'Cosenza',
    'Afragola',
    'Ragusa',
    'Asti',
    'Grosseto',
    'Cremona',
    'Molfetta',
    'Trapani',
    'Carrara',
    'Casoria',
    'Savona',
    'Vigevano',
    'Legnano',
    'Caltanissetta',
    'Potenza',
    'Portici',
    'Matera',
    'San Severo',
    'Cerignola',
    'Trani',
    'Bisceglie',
    'Acerra',
    'Ercolano',
    'Carpi Centro',
    'Imola',
    'Aversa',
    'Bitonto',
    'Venice',
    'Vittoria',
    'Gallarate',
    'Marano di Napoli',
    'Pordenone',
    'Acireale',
    'Scafati',
    'Moncalieri',

    // 100 largest cities from Italy: https://population.mongabay.com/population/italy/
];
